-------------------------------------------------------------------------------
-- Client Script
-------------------------------------------------------------------------------
--¤£¨Ï¥Î
--[[
function MissionTalk_1002()
	C_PortraitDialog( 19 , -64 ,false,false,
					C_GetStringFromPreset( 8250030),
					100)
end
function MissionTalk_1002A()
	C_PortraitDialog( 19 , -64 ,false,false,
					C_GetStringFromPreset( 8250031),
					100)
end
--]]